export class AssetMappings {
  static readonly logoByBrandCode = {
    1: '../../../assets/images/BrandIcons/Delta_logo_400x136.png',
    2: '../../../assets/images/BrandIcons/American_Standard_logo_300x128.png',
    3: '../../../assets/images/BrandIcons/Kohler_logo_sm.png',
    4: '../../../assets/images/BrandIcons/Moen_logo_sm.png',
    5: '../../../assets/images/BrandIcons/Peerless_logo_white_280x90.png',
    6: '../../../assets/images/BrandIcons/Pfister_logo_sm.png',
    7: '../../../assets/images/BrandIcons/Aquasource_logo_white_300x100.png',
    8: '../../../assets/images/BrandIcons/Glacier_Bay_logo_white_400x100.jpg',
    9: '../../../assets/images/BrandIcons/Brizo_logo_900x300.png',
    10: '../../../assets/images/BrandIcons/Grohe_logo_320x136.png',
    11: '../../../assets/images/BrandIcons/Hansgrohe_logo_aqua_486x100.png',
    12: '../../../assets/images/BrandIcons/Briggs_logo_white_310x165.jpg',
    13: '../../../assets/images/BrandIcons/Crane_logo_white_210x100.png',
    14: '../../../assets/images/BrandIcons/Eljer_logo_280x80.png',
    15: '../../../assets/images/BrandIcons/Gerber_logo_700x263.png',
    16: '../../../assets/images/BrandIcons/Jacuzzi_logo_250x100.png',
    17: '../../../assets/images/BrandIcons/Mansfield_logo_blue_430x96.png',
    18: '../../../assets/images/BrandIcons/Sterling_logo_white_634x128.jpg',
    19: '../../../assets/images/BrandIcons/Toto_logo_500x204.png',
    20: '../../../assets/images/BrandIcons/Penguin_logo_425x150.jpg',
    21: '../../../assets/images/BrandIcons/Danze_logo_630x305.png',
    22: '../../../assets/images/BrandIcons/Speakman_logo_800x238.png',
    23: '../../../assets/images/BrandIcons/Waterpik_logo_765x244.png',
    24: '../../../assets/images/BrandIcons/Symmons_logo_420x150.png',
    25: '../../../assets/images/BrandIcons/Aquatic_logo_257x90.png',
    26: '../../../assets/images/BrandIcons/Maax_logo_1478x502.png',
    27: '../../../assets/images/BrandIcons/ASB_logo_blue.gray_100x60.jpg',
    28: '../../../assets/images/BrandIcons/StyleSelections_logo_black_400x110.png',
    29: '../../../assets/images/BrandIcons/Allen-Roth_logo_brown_450x100.png',
    30: '../../../assets/images/BrandIcons/Swan_logo_250x100.png',
    31: '../../../assets/images/BrandIcons/AquaGlass_logo_372x77.gif',
    32: '../../../assets/images/BrandIcons/Proflo_logo_white_290x135.jpg',
    33: '../../../assets/images/BrandIcons/Duravit_logo_500x204.png',
    34: '../../../assets/images/BrandIcons/Mirabelle_logo_401x119.png',
    35: '../../../assets/images/BrandIcons/Villeroy_Boch_logo_blue_240x130.png',
    36: '../../../assets/images/BrandIcons/Decolav_logo_white_580x125.png',
    37: '../../../assets/images/BrandIcons/Rohl_logo_425x135.png',
    38: '../../../assets/images/BrandIcons/Victoria-Albert_logo_344x112.png',
    39: '../../../assets/images/BrandIcons/Ronbow_logo_500x200.png',
    40: '../../../assets/images/BrandIcons/Vortens_logo_222x88.png',
    41: '../../../assets/images/BrandIcons/Oxygenics_logo_white_308x171.jpg',
    42: '../../../assets/images/BrandIcons/MTI_logo_150x150.png',
    43: '../../../assets/images/BrandIcons/otherNotAware.jpg',
    44: '../../../assets/images/BrandIcons/Home_improvment.jpg',
    45: '../../../assets/images/BrandIcons/Sears.jpg',
    46: '../../../assets/images/BrandIcons/Ge.jpg',
    47: '../../../assets/images/BrandIcons/otherstore.jpg'
    // 43: '../../../assets/images/BrandIcons/Oxygenics_logo_white_308x171.jpg',
  };
  static readonly brandNameAndCodes = {
    1: 'Delta',
    2: 'American Standard',
    3: 'Kohler',
    4: 'Moen',
    5: 'Peerless',
    6: 'Pfister',
    7: 'Aqua Source',
    8: 'Glacier Bay',
    9: 'Brizo',
    10: 'Grohe',
    11: 'Hansgrohe',
    12: 'Briggs',
    13: 'Crane',
    14: 'Eljer',
    15: 'Gerber',
    16: 'Jacuzzi',
    17: 'Mansfield',
    18: 'Sterling',
    19: 'Toto',
    20: 'Penguin',
    21: 'Danze',
    22: 'Speakman',
    23: 'Waterpik',
    24: 'Symmons',
    25: 'Aquatic',
    26: 'Maax',
    27: 'ASB',
    28: 'Style Selections',
    29: 'Allen & Roth',
    30: 'Swan',
    31: 'Aqua Glass',
    32: 'Proflo',
    33: 'Duravit',
    34: 'Mirabelle',
    35: 'Villeroy & Boch',
    36: 'Decolav',
    37: 'Rohl',
    38: 'Victoria & Albert',
    39: 'Ronbow',
    40: 'Vortens',
    41: 'Oxygenics',
    42: 'MTI',
    43: "Others/Not aware of any of the above",
    44: "Home Improvement Stores",
    45: "Sears/Kenmore",
    46: "GE",
    47: "Other Store Brands",
    48: "None/Nothing",
    49: "Don`t know",
    50: "Decline to answer",
  };
  static readonly logobyAdds = {
    "The Perfect Touch": '../../../assets/images/addsIcon/Perfect Touch.jpg',
    "Hydrorain One": '../../../assets/images/addsIcon/Hydrorain.jpg',
    "Shield Yourself": '../../../assets/images/addsIcon/Shield Yourself.jpg',
    "Quality Product Touchless KF": '../../../assets/images/addsIcon/Quality Product Touchless.jpg',
    "Lysol ActiClean Self-Clean": '../../../assets/images/addsIcon/Lysol Acticlean Self Clean.jpg',
    "Innovative": '../../../assets/images/addsIcon/Innovative.jpg',
    "Mother Nature": '../../../assets/images/addsIcon/Mother Nature.jpg',
    "Konnect-Pouring Made Easy": '../../../assets/images/addsIcon/Konnect Pouring Made Easy.jpg',
    "Verdera Voice Mirror": '../../../assets/images/addsIcon/Verdera Voice Mirror.jpg',
    "The Design": '../../../assets/images/addsIcon/Design.jpg',
    "Life Designs/ Water is Life": '../../../assets/images/addsIcon/Life Designs_Water is life.jpg',
    "Perfect Fit/In Control": '../../../assets/images/addsIcon/Perfect Fit_In Control.jpg',
    "In2ition Two-In-One": '../../../assets/images/addsIcon/In2ition Two-In-One.jpg',
    "Rough Water/In Control": '../../../assets/images/addsIcon/Rough Water In Control.jpg',
    "Moen Flow": '../../../assets/images/addsIcon/Moen Flow Prescious Liquid.jpg'
  };
  static readonly retailersList = {
    1: 'Home Depot',
    2: "Lowe's",
    3: 'Menards',
    4: 'Kitchen and bath speciality store/showroom',
    5: 'Plumbing supply store/showroom',
    6: 'Kmart',
    7: 'Target',
    8: 'Walmart',
    9: 'Bed Bath & Beyond',
    10: 'Sams Club',
    11: 'Costco',
    12: 'Amazon.com',
    13: 'Build.com',
    14: 'Ebay.com',
    15: 'eFaucets.com',
    16: 'FaucetDirect.com',
    17: 'Other',
    18: 'Dont know'
  };

  static readonly brandCodeByName = {
    'Delta': 1,
    'American Standard': 2,
    'Kohler': 3,
    'Moen': 4,
    'Peerless': 5,
    'Pfister': 6,
    'Aqua Source': 7,
    'Glacier Bay': 8,
    'Brizo': 9,
    'Grohe': 10,
    'Hansgrohe': 11,
    'Briggs': 12,
    'Crane': 13,
    'Eljer': 14,
    'Gerber': 15,
    'Jacuzzi': 16,
    'Mansfield': 17,
    'Sterling': 18,
    'Toto': 19,
    'Penguin': 20,
    'Danze': 21,
    'Speakman': 22,
    'Waterpik': 23,
    'Symmons': 24,
    'Aquatic': 25,
    'Maax': 26,
    'ASB': 27,
    'Style Selections': 28,
    'Allen & Roth': 29,
    'Swan': 30,
    'Aqua Glass': 31,
    'Proflo': 32,
    'Duravit': 33,
    'Mirabelle': 34,
    'Villeroy & Boch': 35,
    'Decolav': 36,
    'Rohl': 37,
    'Victoria & Albert': 38,
    'Ronbow': 39,
    'Vortens': 40,
    'Oxygenics': 41,
    'MTI': 42,
    'Others/Not aware of any of the above': 43,
    'Home Improvement Stores': 44,
    'Sears/Kenmore': 45,
    'GE': 46,
    'Other Store Brands': 47,
    'None/Nothing': 48,
    'Don`t know': 49,
    'Decline to answer': 50,
  };

  static readonly logoByBrandText = {};
}
